version: '3'
services:
  nextjs:
    container_name: nextjs
    build: ./client

    depends_on:
      - web
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
  web:
    build: ./api
    container_name: web
    ports:
      - "8800:8800"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/:/data/db/
